# Fraud detection in Bank transaction
Author: David Moncivais | June 18 2026

## Introduction
### Objective
The objectives of this project is to use the data available to train a model to detect fraud in bank transactions, and in consequence the second being to use it as a practice exerciese for data presentantion, feature engineering, model selection, hyperparameter tuning, and the interpretation of results through data visualization.
### The data
The data is a large-scale synthetic banking dataset simulating 1,000,000 real-world financial transactions across 10 countries, designed for fraud detection and financial risk analysis. 
#### The overview
- **Rows**: 1,000,000
- **Columns**: 26
- **Fraud Rate**: ~5.5% (realistic imbalanced classification)
- **Time Period**: 2020 - 2024

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = './Data/bank_fraud.csv'
df = pd.read_csv(data)
df.head(5)

,transaction_id,customer_id,transaction_date,transaction_time,hour_of_day,is_weekend,is_night_transaction,country,city,merchant_category,...,transaction_amount,num_prev_transactions,transaction_freq_monthly,distance_from_home_km,time_since_last_txn_hrs,is_international,failed_attempts,pin_changed_recently,is_fraud,fraud_type
0,TXN0000000001,CUST00121959,2023-08-17,21:13:00,21,0,0,USA,London,Grocery,...,39.49,157,23,52.7,10.20,0,0,0,0,NaN
1,TXN0000000002,CUST00146868,2024-02-06,05:16:00,5,0,1,UK,New York,Healthcare,...,153.71,153,23,0.9,12.47,0,0,0,0,NaN
2,TXN0000000003,CUST00131933,2024-06-28,12:15:00,12,0,0,Canada,Delhi,Grocery,...,118.20,161,20,9.2,0.08,0,1,0,0,NaN
3,TXN0000000004,CUST00103695,2023-03-16,02:53:00,2,0,1,France,Tokyo,Utilities,...,49.50,160,25,14.8,17.94,1,0,1,1,Synthetic Identity
4,TXN0000000005,CUST00119880,2024-07-12,12:39:00,12,0,0,Canada,Melbourne,Clothing,...,30.74,134,18,38.9,2.16,0,0,0,0,NaN

In [3]:
df.describe()

,hour_of_day,is_weekend,is_night_transaction,customer_age,credit_score,account_age_years,account_balance,transaction_amount,num_prev_transactions,transaction_freq_monthly,distance_from_home_km,time_since_last_txn_hrs,is_international,failed_attempts,pin_changed_recently,is_fraud
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,11.496978,0.286022,0.375057,41.771678,679.028781,4.987911,16594.25442,204.724665,149.996350,19.999322,20.009890,12.000945,0.149994,0.380072,0.080439,0.055255
std,6.923751,0.451900,0.484138,13.424588,78.828748,4.925949,28171.46068,459.567802,12.244379,4.474045,20.011427,11.999904,0.357066,0.914603,0.271972,0.228477
min,0.000000,0.000000,0.000000,18.000000,300.000000,0.100000,100.00000,1.000000,96.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.000000,0.000000,0.000000,32.000000,625.000000,1.400000,3609.01750,33.400000,142.000000,17.000000,5.800000,3.450000,0.000000,0.000000,0.000000,0.000000
50%,11.000000,0.000000,0.000000,42.000000,680.000000,3.500000,8092.12000,73.120000,150.000000,20.000000,13.900000,8.320000,0.000000,0.000000,0.000000,0.000000
75%,18.000000,1.000000,1.000000,51.000000,734.000000,6.900000,18225.02500,181.450000,158.000000,23.000000,27.700000,16.630000,0.000000,0.000000,0.000000,0.000000
max,23.000000,1.000000,1.000000,85.000000,850.000000,30.000000,500000.00000,46129.600000,213.000000,44.000000,292.100000,154.200000,1.000000,5.000000,1.000000,1.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 26 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   transaction_id            1000000 non-null  object
 1   customer_id               1000000 non-null  object
 2   transaction_date          1000000 non-null  object
 3   transaction_time          1000000 non-null  object
 4   hour_of_day               1000000 non-null  int64
 5   is_weekend                1000000 non-null  int64
 6   is_night_transaction      1000000 non-null  int64
 7   country                   1000000 non-null  object
 8   city                      1000000 non-null  object
 9   merchant_category         1000000 non-null  object
 10  payment_method            1000000 non-null  object
 11  device_type               1000000 non-null  object
 12  customer_age              1000000 non-null  int64
 13  credit_score              1000000 non-null  int64
 14  account_age_years         1000000 non-null  float64
 15  account_balance           1000000 non-null  float64
 16  transaction_amount        1000000 non-null  float64
 17  num_prev_transactions     1000000 non-null  int64
 18  transaction_freq_monthly  1000000 non-null  int64
 19  distance_from_home_km     1000000 non-null  float64
 20  time_since_last_txn_hrs   1000000 non-null  float64
 21  is_international          1000000 non-null  int64
 22  failed_attempts           1000000 non-null  int64
 23  pin_changed_recently      1000000 non-null  int64
 24  is_fraud                  1000000 non-null  int64
 25  fraud_type                55255 non-null    object
dtypes: float64(5), int64(11), object(10)
memory usage: 198.4+ MB